// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0L1-qZz2rYmvYa7VvdLxgkSRongXmdI',
    appId: '1:850097869143:web:ac75063ab728b739d0ee12',
    messagingSenderId: '850097869143',
    projectId: 'flutter-login-513d6',
    authDomain: 'flutter-login-513d6.firebaseapp.com',
    storageBucket: 'flutter-login-513d6.appspot.com',
    measurementId: 'G-YF0QWNVY22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT4kHX23RwnS_Gv3MlDvtB7VaTa06fWRk',
    appId: '1:850097869143:android:131a9de2c4b718e3d0ee12',
    messagingSenderId: '850097869143',
    projectId: 'flutter-login-513d6',
    storageBucket: 'flutter-login-513d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXIOkDgPRMnyEm6ZQNeCLBpBv8UQx1cc',
    appId: '1:850097869143:ios:cff8e15028faa6e8d0ee12',
    messagingSenderId: '850097869143',
    projectId: 'flutter-login-513d6',
    storageBucket: 'flutter-login-513d6.appspot.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXIOkDgPRMnyEm6ZQNeCLBpBv8UQx1cc',
    appId: '1:850097869143:ios:b6ff591aec45db09d0ee12',
    messagingSenderId: '850097869143',
    projectId: 'flutter-login-513d6',
    storageBucket: 'flutter-login-513d6.appspot.com',
    iosBundleId: 'com.example.flutterLogin.RunnerTests',
  );
}
